version: "3"
services:
  rest-backend:
    image: wizardzloy/client-side-graphql-rest-backend
    ports:
      - "3000:3000"
  graphql-schema:
    image: wizardzloy/client-side-graphql-graphql-schema
    ports:
      - "4000:4000"
  client-app:
    image: wizardzloy/client-side-graphql-client-app
    ports:
      - "5000:5000"
